// Renders the DB-backed exam set into the exact `const APPLICATIONS=[...]`
// shape the frontend (app.js's UI logic, plus index.html/exams.html/
// calendar.html which load this before app.js) already expects. This file
// is the DB-generated replacement for what used to be a hand-written
// literal inside app.js itself — see bin/publish.js for how it's staged
// and atomically swapped into data/applications.generated.js alongside the
// other publish outputs.
function renderApplicationsJs(exams) {
  return (
    `// AUTO-GENERATED by monitor/bin/publish.js — do not edit by hand.\n` +
    `// This is GovBabu's exam data, generated from the monitor database.\n` +
    `// To change it: edit via the admin dashboard (monitor/admin/) or let\n` +
    `// the monitoring pipeline detect + you approve a real change, then\n` +
    `// run \`npm run publish:site\` again.\n` +
    `const APPLICATIONS=${JSON.stringify(exams)};\n`
  );
}

module.exports = { renderApplicationsJs };
