const { SITE_ORIGIN } = require('./render');

// The static top-level pages that already exist at the repo root — kept as
// a small explicit list rather than scanned from disk, since it's a fixed,
// rarely-changing set and an explicit list is easier to reason about than
// directory-scanning logic that could accidentally pick up something it
// shouldn't (e.g. applications.html, which is still just a redirect stub —
// tools.html used to be one too, but is now a real page of its own).
const STATIC_PAGES = [
  { path: '/index.html', priority: '1.0' },
  { path: '/exams.html', priority: '0.9' },
  { path: '/calendar.html', priority: '0.5' },
  { path: '/tools.html', priority: '0.5' },
  { path: '/about.html', priority: '0.5' },
  { path: '/contact.html', priority: '0.5' },
  { path: '/privacy.html', priority: '0.3' },
  { path: '/terms.html', priority: '0.3' },
  { path: '/disclaimer.html', priority: '0.3' },
];

function xmlEscape(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

// lastmod is optional per the sitemap protocol. Static top-level pages
// (index.html, exams.html, ...) aren't generated by this pipeline and this
// script has no real modification-date source for them — claiming they
// changed "today" on every publish run, when they didn't, is exactly the
// kind of false-freshness signal that erodes a crawler's trust in a site's
// lastmod values over time. So static pages simply omit <lastmod>. Exam
// pages DO have a genuine, content-derived date (field_history-backed
// exams.updated_at, already threaded through as e.lastUpdated) and use it.
function buildSitemap(exams) {
  const urls = [
    ...STATIC_PAGES.map((p) => ({ loc: `${SITE_ORIGIN}${p.path}`, priority: p.priority })),
    ...exams.map((e) => ({ loc: `${SITE_ORIGIN}/exams/${e.slug}/`, lastmod: e.lastUpdated ? e.lastUpdated.slice(0, 10) : null, priority: '0.8' })),
  ];
  const body = urls
    .map((u) => `  <url>\n    <loc>${xmlEscape(u.loc)}</loc>${u.lastmod ? `\n    <lastmod>${u.lastmod}</lastmod>` : ''}\n    <priority>${u.priority}</priority>\n  </url>`)
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;
}

module.exports = { buildSitemap, STATIC_PAGES };
